pagina_estatica:
    path:     /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    
_pagina_estatica:
    path:  /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: pagina_estatica, permanent: true }
    
oferta:
    path:     /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }
