ciudad_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CiudadBundle:Default:index }

ciudad_recientes:
    path:     /{ciudad}/recientes.{_format}
    defaults: { _controller: CiudadBundle:Default:recientes, _format: html }
    requirements:
        _format: html|rss