backend_ciudades:
    pattern:  /
    defaults: { _controller: "CiudadBundle:Ciudad:index" }

backend_ciudades_show:
    pattern:  /{id}/show
    defaults: { _controller: "CiudadBundle:Ciudad:show" }

backend_ciudades_new:
    pattern:  /new
    defaults: { _controller: "CiudadBundle:Ciudad:new" }

backend_ciudades_create:
    pattern:  /create
    defaults: { _controller: "CiudadBundle:Ciudad:create" }
    requirements: { _method: post }

backend_ciudades_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CiudadBundle:Ciudad:edit" }

backend_ciudades_update:
    pattern:  /{id}/update
    defaults: { _controller: "CiudadBundle:Ciudad:update" }
    requirements: { _method: post|put }

backend_ciudades_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CiudadBundle:Ciudad:delete" }
    requirements: { _method: post|delete }
