backend_ofertas:
    pattern:  /
    defaults: { _controller: "BackendBundle:Oferta:index" }

backend_ofertas_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Oferta:show" }

backend_ofertas_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Oferta:new" }

backend_ofertas_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Oferta:create" }
    requirements: { _method: post }

backend_ofertas_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Oferta:edit" }

backend_ofertas_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Oferta:update" }
    requirements: { _method: post|put }

backend_ofertas_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Oferta:delete" }
    requirements: { _method: post|delete }
