# src/Cupon/BackendBundle/Resources/config/routing.yml

backend_ciudad_cambiar:
    path:     /cambiar-a-{ciudad}
    defaults: { _controller: BackendBundle:Default:ciudadCambiar }

backend_portada:
    path:     /
    defaults: { _controller: BackendBundle:Oferta:index }
    
BackendOferta:
    resource: "@BackendBundle/Resources/config/oferta.yml"
    prefix:   /ofertas

BackendCiudad:
    resource: "@BackendBundle/Resources/config/ciudad.yml"
    prefix:   /ciudades

BackendTienda:
    resource: "@BackendBundle/Resources/config/tienda.yml"
    prefix:   /tiendas
    
BackendUsuario:
    resource: "@BackendBundle/Resources/config/usuario.yml"
    prefix:   /usuarios

BackendVenta:
    resource: "@BackendBundle/Resources/config/venta.yml"
    prefix:   /ventas
