# src/Cupon/BackendBundle/Resources/config/routing.yml

backend_ciudad_cambiar:
    path:     /cambiar-a-{ciudad}
    defaults: { _controller: BackendBundle:Default:ciudadCambiar }

backend_portada:
    path:     /
    defaults: { _controller: BackendBundle:Oferta:index }
    
    
BackendOferta:
    resource: "@BackendBundle/Resources/config/routing/oferta.yml"
    prefix:   /ofertas
    
    
BackendCiudad:
    resource: "@BackendBundle/Resources/config/routing/ciudad.yml"
    prefix:   /ciudad
    
BackendTienda:
    resource: "@BackendBundle/Resources/config/routing/tienda.yml"
    prefix:   /tienda
    
BackendUsuario:
    resource: "@BackendBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario